### ISSUE TITLE
Please add laser guided bombs to the F18 Rearm screen

### ISSUE THREAD

**Issue by ifofo** [Hoggit/TNN2#26]
Hi! I would love to practice JTAC and laser guided bombs with the F18. Please add some Mavericks and other laser guided bombs to the rearm panel.

**Comment by LazyBoot** [comment]
Looks fine on my end...
![image](https://user-images.githubusercontent.com/3827482/54475799-0bfa7100-47f6-11e9-8cfd-ca021e8a38d7.png)

![image](https://user-images.githubusercontent.com/3827482/54475805-1ae12380-47f6-11e9-8c71-954f941e77cd.png)

**Comment by ifofo** [comment]
Ah sorry, my bad - I worded the question wrong. Sorry. I meant: the preset list. Is it possible to make a preset like for e.g. the MK82's?

**Comment by Lugghawk** [comment]
Those presets aren't stored in the mission itself as far as I know. The way you can make more is by going into your own mission editor and adding them through the armaments panel. 

Anything you make there should be available for you inside the game too

**Comment by ifofo** [comment]
Thank you!
