### ISSUE TITLE
Moving to Patreon Tomcat slot and back causes CTD

### ISSUE THREAD

**Issue by gorgefodder** [Hoggit/TNN2#28]
I join GAW, click on my Tomcat slot, go to FLY. Nothing happens, I get a text warning top left "YOUR FLIGHT IS DELAYED PLEASE WAIT". Stennis deck is full so that's fair enough. I click Briefing again to pick a new slot and then I CTD.

Not sure if that's a Slot block problem causing CTD or a DCS thing.

**Comment by Lugghawk** [comment]
Is still a thing? This is a GAW bug though, right?
