### ISSUE TITLE
MiG-29, Su-27, and Su-33 spawns

### ISSUE THREAD

**Issue by DeputyTootle** [Hoggit/TNN2#6]
The only fc3 aircraft in the map is the f-15

**Comment by Lugghawk** [comment]
I'm adding some Migs and Su-27s to Senaki, but the Su-33 will require a coalition fiddle and might take longer. I'm going to close this and open one just for the Su-33s and coalition change.

**Comment by Lugghawk** [comment]
Moved Su-33 spawns to #10.
